name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    # if: ${{ github.ref == 'refs/heads/testBranch' }}
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: extract-branch-name
      shell: bash
      run: echo "::stop-commands::`echo ::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})`"
      id: extract_branch
      
    - name: branch check
      if: (github.ref != 'testBranch')
      run: exit 1
      
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://kornferrydev.crm.dynamics.com/'
        user-name: 'rich.lee@CRM316601.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://kornferrydev.crm.dynamics.com/'
        user-name: 'rich.lee@CRM316601.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: TestSolution
        solution-output-file: out/exported/TestSolution.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/TestSolution.zip
        solution-folder: out/solutions/TestSolution
        solution-type: 'Unmanaged'
        overwrite-files: trueBranch

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/TestSolution
        solution-target-folder: solutions/TestSolution
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
        branch-name: $BRANCH_NAME
