# This is a basic workflow to help you get started with Actions

name: pack and import

# Controls when the action will run. 
on:
  workflow_dispatch:    # allow for manual workflow triggering as needed
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://kornferrydev.crm.dynamics.com/'
        user-name: 'rich.lee@CRM316601.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
    - name: Test pack-solution action
      if: matrix.os == 'windows-latest'   # SoPa.exe is windows only
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        solution-folder: 'out/solutions/TestSolution'
        solution-file: 'out/exported/TestSolution.zip'
        solution-type: 'Unmanaged'
    - name: Test import-solution action with username/password
      if: matrix.os == 'windows-latest'   # The solution we test with here is created in a previous windows-only step
      uses: ./import-solution
      with:
        environment-url: 'https://kornferrydev.crm.dynamics.com/'
        user-name: 'rich.lee@CRM316601.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-file: 'out/CI/emptySolution.zip'
        force-overwrite: true
        run-asynchronously: true

    
